```{r}
## libraries
library(tidycensus)
library(sf)
library(readxl)
library(tidycensus)
library(tigris)
library(here)
library(tidyverse)
library(janitor)
library(skimr)
```

## Calculated comms index does not equal comms index used in feature
```{r}
## loading the index currently on Urban's web feature
## renaming variables so that we can join this to the index calculated in the codebase
## and compare variables that should be the same

comms_2023_actual = read_csv(here("erap_2023_comms_actual.csv")) %>%
  rename(
    total_index_actual = `Total Index (Z-scored Percentile)`,
    housing_subindex_actual = `Housing Subindex (Z-scored Percentile)`,
    hh_chars_subindex_actual = `Household Characteristics Subindex (Z-scored Percentile)`,
    income_subindex_actual = `Income Subindex (Z-scored Percentile)`,
    percent_black_actual = `% Black (Z-scored Percentile)`,
    percent_eli_actual = `% Extremely low–income renters (Z-scored Percentile)`)

data_catalog_2023_actual = read_csv(here("erap_2023_data_catalog_actual.csv"))

## when calculated using updated public-facing repo, 2021 census year
comms_index_testing = comms_index %>%
  select(geoid, total_index_calculated = `Total Index (Z-scored Percentile)`) %>%
  left_join(comms_2023_actual %>% select(geoid, total_index_actual)) %>%
  mutate(
    index_difference = (total_index_actual- total_index_calculated),
    state = str_sub(geoid, 1, 2),
    priority_buckets_actual = case_when(
      total_index_actual >= 95 ~ 1,
      total_index_actual >= 90 ~ 2,
      total_index_actual >= 85 ~ 3,
      total_index_actual >= 75 ~ 4,
      total_index_actual >= 50 ~ 5,
      total_index_actual >= 0 ~ 6,
      TRUE ~ NA),
    priority_buckets_calculated = case_when(
      total_index_calculated >= 95 ~ 1,
      total_index_calculated >= 90 ~ 2,
      total_index_calculated >= 85 ~ 3,
      total_index_calculated >= 75 ~ 4,
      total_index_calculated >= 50 ~ 5,
      total_index_calculated >= 0 ~ 6,
      TRUE ~ NA),
    priority_bucket_change_flag = if_else(priority_buckets_actual != priority_buckets_calculated, 1, 0),
    priority_bucket_difference = abs(priority_buckets_actual - priority_buckets_calculated)) 


## 55% of tracts had a change
comms_index_testing %>%
  filter(!is.na(index_difference)) %>%
  count(index_difference != 0) %>%
  mutate(perc = prop.table(n)) 

## mean difference of .75
comms_index_testing %>%
  summarize(mean_difference = mean(abs(index_difference), na.rm = TRUE)) 

## tracts with a change in total index value of five or more: .3%
comms_index_testing %>%
  count(abs(index_difference) >= 5) %>%
  mutate(perc = prop.table(n))

## of these 
comms_index_testing %>%
  filter(abs(index_difference) >= 5) %>%
  count() %>%
  mutate(perc = prop.table(n))

## 3% of tracts changed priority buckets
comms_index_testing %>%
  count(priority_bucket_change_flag) %>%
  mutate(perc = prop.table(n)) 

## all tracts that changed buckets changed a single bucket
comms_index_testing %>%
  count(priority_bucket_difference) %>%
  mutate(perc = prop.table(n)) 

## only 2% of tracts changed a bucket in one of the higher priority categories (and these changes were all to an adjacent bucket)
comms_index_testing %>%
  count(priority_bucket_change_flag == 1 & (total_index_actual >= 85 | total_index_calculated >= 85)) %>%
  mutate(perc = prop.table(n))

## the distribution of changes is normally distributed around zero
comms_index_testing %>%
  ggplot() +
    #geom_boxplot(aes(index_difference))
    geom_histogram(aes(index_difference))
```
```{r}

```

## Apart from the total index, it appears that all other values are the same
```{r}
comms_index %>% 
  select(
    geoid, 
    housing_subindex_calculated = `Housing Subindex (Z-scored Percentile)`, 
    hh_chars_subindex_calculated = `Household Characteristics Subindex (Z-scored Percentile)`,
    income_subindex_calculated = `Income Subindex (Z-scored Percentile)`,
    percent_black_calculated = `% Black (Z-scored Percentile)`,
    percent_eli_calculated = `% Extremely low–income renters (Z-scored Percentile)`) %>%
  left_join(comms_2023_actual %>% select(
    geoid, housing_subindex_actual, hh_chars_subindex_actual, income_subindex_actual, percent_black_actual, percent_eli_actual)) %>%
  filter(
    housing_subindex_calculated != housing_subindex_actual | 
    hh_chars_subindex_calculated != hh_chars_subindex_actual |  
    income_subindex_calculated != income_subindex_actual |
    percent_black_calculated != percent_black_actual | 
    percent_eli_calculated != percent_eli_actual)
```

## Where did the total index calculation differ? It's not clear...
```{r}
## using the final indicator index because it has the the raw subindex values
## checking that eveything is the same:
# final_indicator_index %>%
#   select(geoid, matches("Z-scored")) %>%
#   st_drop_geometry %>%
#   left_join(comms_index_2021_2018_public_repo %>% 
#   select(
#     geoid, 
#     total_index_calculated = `Total Index (Z-scored Percentile)`,
#     housing_subindex_calculated = `Housing Subindex (Z-scored Percentile)`, 
#     hh_chars_subindex_calculated = `Household Characteristics Subindex (Z-scored Percentile)`,
#     income_subindex_calculated = `Income Subindex (Z-scored Percentile)`))

final_indicator_index %>%
  st_drop_geometry %>%
  select(geoid, matches("index"), state_name) %>% 
  mutate(
    total_index_check = (`Housing Subindex` * outcome_index_weights[1]) + (`Income Subindex` * outcome_index_weights[2]) + (`Household Characteristics Subindex` * outcome_index_weights[3])) %>%
    group_by(state_name) %>%
    ## zscoring by state and transforming to percentiles
    mutate(total_index_check_zscore_percentile = total_index_check %>% scale %>% ntile(n = 100)) %>% 
    ungroup() %>%
  select(geoid, matches("Total")) %>%
  left_join(comms_2023_actual %>% select(geoid, total_index_actual))
  # filter(total_index_check_zscore_percentile != `Total Index (Z-scored Percentile)`)
```

## Did the technical appendix analysis use a different version of the index?
```{r, fig.height = 10, fig.width = 10}
## using the outcome index (2018 indicators), correlations are the same as reported
final_outcome_index %>%
  st_drop_geometry %>%
  select(matches("eviction|index")) %>%
  na.omit() %>%
  cor() %>%
  ggcorrplot::ggcorrplot(type = "lower", lab = TRUE)

## same is true for the indicator index (2021 indicators)
final_indicator_index %>%
  st_drop_geometry %>%
  select(matches("eviction|index")) %>%
  na.omit() %>%
  cor() %>%
  ggcorrplot::ggcorrplot(type = "lower", lab = TRUE)
```

